[[_introduction]]
= Introduction to {this-platform} {this-application} 

{this-platform} {this-application} is an Open Source Java based CAMEL Gateway Platform enabler intended for fast and easy Intelligent Networks (IN) services deployment in mobile networks using CAMEL Application Part (CAP) protocols.
It enables operators to offer real-time  control of voice call, SMS and GPRS sessions in GSM networks, using service logic applications. 

{this-platform} {this-application} strictly adheres to the standards and specifications defined by the International Telecommunications Union (ITU). 

{this-platform} {this-application} acts as an intermediary platform linking the service applications to the GSM network in a session oriented communication.
 

{this-platform} {this-application} is an easy-to-install and easy-to-deploy platform.
The Open Source Software gives you the flexibility to understand the source code.
It is also possible to customise the product to meet your Enterprise needs. 

{this-platform} {this-application} is based on the robust and proven {this-platform} JAIN SLEE 1.1 Server and {this-platform} jSS7 Stack. 

This guide provides detailed information about configuration, supported protocols and compliant standards.
For installation instructions, please refer to the Installation Guide that is included in the product documentation.
For more details about the underlying jSS7 Stack, you can refer to the {this-platform} jSS7 Stack User Guide. 
