[[_setup_configuration]]
= Post Installation Configuration

== Memory Settings

We recommend that you fine-tune the JVM memory settings by allocating a minimum of 3 GB for initial and maximum heap size as shown below.
However, you may choose any settings that better fits your setup. 

-Xms3072m::
  Initial heap size, set in megabytes

-Xmx3072m::
  Maximum heap size, set in megabytes

[[_ss7_camel_settings]]
== Configuring the Gateway

Once you have installed {this-platform} {this-application} , you can go ahead and configure the SS7 Stack and the CAMEL Gateway.
The {this-platform} jSS7 Stack User Guide in the [path]_{this-folder}-camel-<version>/docs/jss7/_ folder will assist you in configuring and managing the SS7 Stack. 

.Configure SS7 before CAMEL Gateway
[NOTE]
====
Make sure you configure the SS7 Stack before configuring the CAMEL Gateway. 
====

The {this-platform} {this-application} Admin Guide in the [path]_{this-folder}-camel-<version>/docs/camel/_ folder will assist you in configuring and managing the CAMEL Gateway.
To configure and manage both the Stack and the Gateway you must use the Command Line Interface (CLI) tool that comes with the platform.
For instructions on starting the Shell and help with commands, please refer to the {this-platform}  {this-application}  Admin Guide. 

[[_dialogic_setup]]
== Extra setup when usage of Dialogic cards

If you use only m3ua stack for communicating via SS7 network we can skip this chapter. If you use legacy dialogic cards with or without m3ua you need to follow actions from this chaper.

.Procedure: Extra actions for dialogic card usage
. Copy gct java lib: `gctApi.jar` from downloaded dialogic drivers (from folder `dpk/JAVA`) into the folder `jboss-5.1.0.GA/server/default/deploy/{this-folder}-camel-gateway/lib`.
. Copy native lib: `libgctjni.so` from downloaded dialogic drivers (from folder `dpk/64` or `dpk/32` depending on JAVA 64 or 32-bit version) into the folder `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x64` for JAVA 64-bit or `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x86` for JAVA 32-bit.
. Copy jboss mbean config files: `jboss-beans.xml` and `jboss-structure.xml` files from `template/META-INF-dialogic` folder (if we use dialogic boards WITHOUT m3ua) or from `template/META-INF-m3ua-dialogic` folder (if we use dialogic boards WITH m3ua together) to folder `jboss-5.1.0.GA/server/default/deploy/{this-folder}-camel-gateway/META-INF`
. In the copied `jboss-beans.xml` file you need to find a bean with DialogicMtp3UserPart class and update properties `sourceModuleId` and `destinationModuleId` with modules ids that are configured in your dialogc board.
