= Introduction

{this-platform} {this-application} is an Open Source Java based CAMEL Gateway Platform that routes CAMEL messages between signaling network and service applications.
 

{this-platform} {this-application} acts as an intermediary platform linking the service applications to the GSM network in a session oriented communication. {this-platform} {this-application} is an easy-to-install and easy-to-deploy platform.
 

{this-platform} {this-application} supports TDM hardware offered by major vendors in the market, namely Intel family boards (Dialogic) and  Zaptel/Dahdi (Digium, Sangoma). TeleStax also offrers an in-house SS7 cards known as Restcomm SS7 Cards.
Restcomm SS7 cards have on-board MTP2/3 support.
Using Restcomm SS7 cards reduces the processing load on the server hosting the {this-platform} {this-application} platform.
 

{this-platform} {this-application} is based on the robust and proven {this-platform} JAIN SLEE 1.1 Server and {this-platform} jSS7 Stack. {this-platform} JAIN SLEE Server is a highly scalable event-driven application server with a robust component model and fault tolerant execution environment.
It provides a set of connectors to a variety of networks elements: SS7 MAP, TCAP, INAP, ISUP, SMPP, XMPP, SIP, MGCP, HTTP, XDM, XCAP, Diameter and many more.
It is fully compliant with JSR 240 (JSLEE 1.1). {this-platform} jSS7 is a software based implementation of the SS7 protocol.
It provides implementation for Level 2 and above in the SS7 protocol Stack. {this-platform} jSS7 Stack User Guide is included for your convenience.
You can refer to the guide for more details on the Stack. 

The {this-platform} CAMEL Gateway makes use of HTTP protocol between the gateway and the third-party applications (or Value Added Service Modules). {this-platform} USSD Gateway receives the USSD request from the subscriber's handset/device via the GSM Signaling network and then translates these requests to HTTP depending on the rules configured in the Gateway.
The traffic can be routed to a corresponding Value Added Service (VAS) or third-party application.
The HTTP callback mechanism allows third-party applications to be developed independent of the underlying Operating System, Programming Language and Framework. 

This guide will assist you with installing {this-platform} {this-application} .
For more details on configuring and using the platform, please refer to the {this-platform} {this-application} User Guide.
 
